// Date: 2016-06-10 23:07:06
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.fogo01.scicraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelAlienAnt extends ModelBase {
    //fields
    ModelRenderer Head;
    ModelRenderer Body;
    ModelRenderer Butt;
    ModelRenderer Leg1;
    ModelRenderer Leg2;
    ModelRenderer Leg3;
    ModelRenderer Leg4;
    ModelRenderer Leg5;
    ModelRenderer Leg6;

    public ModelAlienAnt() {
        textureWidth = 64;
        textureHeight = 64;
    
        Head = new ModelRenderer(this, 32, 0);
        Head.addBox(-4F, -4F, -8F, 8, 8, 8);
        Head.setRotationPoint(0F, 20F, -3F);
        Head.setTextureSize(64, 64);
        Head.mirror = true;
        setRotation(Head, -0.1745329F, 0F, 0F);
        Body = new ModelRenderer(this, 0, 0);
        Body.addBox(-3F, -3F, -3F, 6, 10, 6);
        Body.setRotationPoint(0F, 20F, 0F);
        Body.setTextureSize(64, 64);
        Body.mirror = true;
        setRotation(Body, 1.745329F, 0F, 0F);
        Butt = new ModelRenderer(this, 0, 16);
        Butt.addBox(-5F, -3F, -3F, 10, 8, 10);
        Butt.setRotationPoint(0F, 17F, 8F);
        Butt.setTextureSize(64, 64);
        Butt.mirror = true;
        setRotation(Butt, 0.3490659F, 0F, 0F);
        Leg1 = new ModelRenderer(this, 40, 16);
        Leg1.addBox(-9F, -1F, -1F, 10, 2, 2);
        Leg1.setRotationPoint(-4F, 20F, 2F);
        Leg1.setTextureSize(64, 64);
        Leg1.mirror = true;
        setRotation(Leg1, 0F, 0.5759587F, -0.3490659F);
        Leg2 = new ModelRenderer(this, 40, 16);
        Leg2.addBox(-9F, -1F, -1F, 10, 2, 2);
        Leg2.setRotationPoint(-4F, 20F, 0.5F);
        Leg2.setTextureSize(64, 64);
        Leg2.mirror = true;
        setRotation(Leg2, 0F, 0F, -0.3490659F);
        Leg3 = new ModelRenderer(this, 40, 16);
        Leg3.addBox(-9F, -1F, -1F, 10, 2, 2);
        Leg3.setRotationPoint(-4F, 20F, -1F);
        Leg3.setTextureSize(64, 64);
        Leg3.mirror = true;
        setRotation(Leg3, 0F, -0.5759587F, -0.3490659F);
        Leg4 = new ModelRenderer(this, 40, 20);
        Leg4.addBox(-1F, -1F, -1F, 10, 2, 2);
        Leg4.setRotationPoint(4F, 20F, 2F);
        Leg4.setTextureSize(64, 64);
        Leg4.mirror = true;
        setRotation(Leg4, 0F, -0.5759587F, 0.3490659F);
        Leg5 = new ModelRenderer(this, 40, 20);
        Leg5.addBox(-1F, -1F, -1F, 10, 2, 2);
        Leg5.setRotationPoint(4F, 20F, 0.5F);
        Leg5.setTextureSize(64, 64);
        Leg5.mirror = true;
        setRotation(Leg5, 0F, 0F, 0.3490659F);
        Leg6 = new ModelRenderer(this, 40, 20);
        Leg6.addBox(-1F, -1F, -1F, 10, 2, 2);
        Leg6.setRotationPoint(4F, 20F, -1F);
        Leg6.setTextureSize(64, 64);
        Leg6.mirror = true;
        setRotation(Leg6, 0F, 0.5759587F, 0.3490659F);
    }
  
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Head.render(f5);
        Body.render(f5);
        Butt.render(f5);
        Leg1.render(f5);
        Leg2.render(f5);
        Leg3.render(f5);
        Leg4.render(f5);
        Leg5.render(f5);
        Leg6.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);

        this.Head.rotateAngleY = f3 / (180F / (float)Math.PI);
        this.Head.rotateAngleX = f4 / (180F / (float)Math.PI);

        this.Leg1.rotateAngleY = MathHelper.cos(f * 0.6662f) * 0.8f * f1 + 0.5759587F;
        this.Leg2.rotateAngleY = MathHelper.cos(f * 0.6662f + (float)Math.PI) * 0.8f * f1;
        this.Leg3.rotateAngleY = MathHelper.cos(f * 0.6662f) * 0.8f * f1 - 0.5759587F;

        this.Leg4.rotateAngleY = MathHelper.cos(f * 0.6662f + (float)Math.PI) * 0.8f * f1 - 0.5759587F;
        this.Leg5.rotateAngleY = MathHelper.cos(f * 0.6662f) * 0.8f * f1;
        this.Leg6.rotateAngleY = MathHelper.cos(f * 0.6662f + (float)Math.PI) * 0.8f * f1 + 0.5759587F;

        this.Butt.rotateAngleY = MathHelper.cos(f * 0.6662f) * 0.4f * f1;
    }
}
