// Date: 2016-08-20 19:05:22
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.fogo01.scicraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLaserRifle extends ModelBase {
    //fields
    ModelRenderer Handle;
    ModelRenderer CoreBase;
    ModelRenderer CoreBack;
    ModelRenderer CoreFront;
    ModelRenderer Barrel;
    ModelRenderer LaserCoil0;
    ModelRenderer LaserCoil1;
    ModelRenderer LaserCoil2;
    ModelRenderer LaserCoil3;

    public ModelLaserRifle() {
        textureWidth = 64;
        textureHeight = 32;

        Handle = new ModelRenderer(this, 0, 0);
        Handle.addBox(-0.5F, -2F, -1F, 1, 3, 1);
        Handle.setRotationPoint(0F, 0F, 0F);
        Handle.setTextureSize(64, 32);
        Handle.mirror = true;
        setRotation(Handle, 0F, 0F, 0F);
        CoreBase = new ModelRenderer(this, 6, 3);
        CoreBase.addBox(-7F, -3F, -1F, 12, 1, 2);
        CoreBase.setRotationPoint(0F, 0F, 0F);
        CoreBase.setTextureSize(64, 32);
        CoreBase.mirror = true;
        setRotation(CoreBase, 0F, 1.570796F, 0F);
        CoreBack = new ModelRenderer(this, 34, 3);
        CoreBack.addBox(-1F, -5F, 6F, 2, 2, 1);
        CoreBack.setRotationPoint(0F, 0F, 0F);
        CoreBack.setTextureSize(64, 32);
        CoreBack.mirror = true;
        setRotation(CoreBack, 0F, 0F, 0F);
        CoreFront = new ModelRenderer(this, 6, 6);
        CoreFront.addBox(-1F, -5F, -1F, 5, 2, 2);
        CoreFront.setRotationPoint(0F, 0F, 0F);
        CoreFront.setTextureSize(64, 32);
        CoreFront.mirror = true;
        setRotation(CoreFront, 0F, 1.570796F, 0F);
        Barrel = new ModelRenderer(this, 4, 0);
        Barrel.addBox(-6F, -4.5F, -0.5F, 19, 2, 1);
        Barrel.setRotationPoint(0F, 0F, 0F);
        Barrel.setTextureSize(64, 32);
        Barrel.mirror = true;
        setRotation(Barrel, 0F, 1.570796F, 0F);
        LaserCoil0 = new ModelRenderer(this, 0, 4);
        LaserCoil0.addBox(-1F, -5F, 4.8F, 2, 2, 1);
        LaserCoil0.setRotationPoint(0F, 0F, 0F);
        LaserCoil0.setTextureSize(64, 32);
        LaserCoil0.mirror = true;
        setRotation(LaserCoil0, 0F, 0F, 0F);
        LaserCoil1 = new ModelRenderer(this, 0, 4);
        LaserCoil1.addBox(-1F, -5F, 3.6F, 2, 2, 1);
        LaserCoil1.setRotationPoint(0F, 0F, 0F);
        LaserCoil1.setTextureSize(64, 32);
        LaserCoil1.mirror = true;
        setRotation(LaserCoil1, 0F, 0F, 0F);
        LaserCoil2 = new ModelRenderer(this, 0, 4);
        LaserCoil2.addBox(-1F, -5F, 2.4F, 2, 2, 1);
        LaserCoil2.setRotationPoint(0F, 0F, 0F);
        LaserCoil2.setTextureSize(64, 32);
        LaserCoil2.mirror = true;
        setRotation(LaserCoil2, 0F, 0F, 0F);
        LaserCoil3 = new ModelRenderer(this, 0, 4);
        LaserCoil3.addBox(-1F, -5F, 1.2F, 2, 2, 1);
        LaserCoil3.setRotationPoint(0F, 0F, 0F);
        LaserCoil3.setTextureSize(64, 32);
        LaserCoil3.mirror = true;
        setRotation(LaserCoil3, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Handle.render(f5);
        CoreBase.render(f5);
        CoreBack.render(f5);
        CoreFront.render(f5);
        Barrel.render(f5);
        LaserCoil0.render(f5);
        LaserCoil1.render(f5);
        LaserCoil2.render(f5);
        LaserCoil3.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }
}
