// Date: 2016-06-18 15:27:21
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.fogo01.scicraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelRocketBooster extends ModelBase {
    //fields
    ModelRenderer Booster1SideBack;
    ModelRenderer Booster1SideLeft;
    ModelRenderer Booster1SideFront;
    ModelRenderer Booster1SideRight;
    ModelRenderer Booster1SideLB;
    ModelRenderer Booster1SideBR;
    ModelRenderer Booster1SideRF;
    ModelRenderer Booster1SideFL;
    ModelRenderer Booster1NozzleBack;
    ModelRenderer Booster1NozzleLeft;
    ModelRenderer Booster1NozzleFront;
    ModelRenderer Booster1NozzleRight;
    ModelRenderer Booster1NozzleLB;
    ModelRenderer Booster1NozzleBR;
    ModelRenderer Booster1NozzleFL;
    ModelRenderer Booster1NozzleRF;
    ModelRenderer Booster1ConeBack;
    ModelRenderer Booster1ConeLB;
    ModelRenderer Booster1ConeLeft;
    ModelRenderer Booster1ConeFL;
    ModelRenderer Booster1ConeFront;
    ModelRenderer Booster1ConeRF;
    ModelRenderer Booster1ConeRight;
    ModelRenderer Booster1ConeBR;
    ModelRenderer Booster1ConeTop;

    public ModelRocketBooster() {
        textureWidth = 32;
        textureHeight = 64;

        Booster1SideBack = new ModelRenderer(this, 0, 9);
        Booster1SideBack.addBox(-1.5F, 0F, 2.6F, 3, 48, 1);
        Booster1SideBack.setRotationPoint(0F, 0F, 0F);
        Booster1SideBack.setTextureSize(32, 64);
        Booster1SideBack.mirror = true;
        setRotation(Booster1SideBack, 0F, 0F, 0F);
        Booster1SideLeft = new ModelRenderer(this, 0, 9);
        Booster1SideLeft.addBox(-1.5F, 0F, 2.6F, 3, 48, 1);
        Booster1SideLeft.setRotationPoint(0F, 0F, 0F);
        Booster1SideLeft.setTextureSize(32, 64);
        Booster1SideLeft.mirror = true;
        setRotation(Booster1SideLeft, 0F, 1.570796F, 0F);
        Booster1SideFront = new ModelRenderer(this, 0, 9);
        Booster1SideFront.addBox(-1.5F, 0F, 2.6F, 3, 48, 1);
        Booster1SideFront.setRotationPoint(0F, 0F, 0F);
        Booster1SideFront.setTextureSize(32, 64);
        Booster1SideFront.mirror = true;
        setRotation(Booster1SideFront, 0F, 3.141593F, 0F);
        Booster1SideRight = new ModelRenderer(this, 0, 9);
        Booster1SideRight.addBox(-1.5F, 0F, 2.6F, 3, 48, 1);
        Booster1SideRight.setRotationPoint(0F, 0F, 0F);
        Booster1SideRight.setTextureSize(32, 64);
        Booster1SideRight.mirror = true;
        setRotation(Booster1SideRight, 0F, -1.570796F, 0F);
        Booster1SideLB = new ModelRenderer(this, 0, 9);
        Booster1SideLB.addBox(-1.5F, 0F, 2.6F, 3, 48, 1);
        Booster1SideLB.setRotationPoint(0F, 0F, 0F);
        Booster1SideLB.setTextureSize(32, 64);
        Booster1SideLB.mirror = true;
        setRotation(Booster1SideLB, 0F, 0.7853982F, 0F);
        Booster1SideBR = new ModelRenderer(this, 0, 9);
        Booster1SideBR.addBox(-1.5F, 0F, 2.6F, 3, 48, 1);
        Booster1SideBR.setRotationPoint(0F, 0F, 0F);
        Booster1SideBR.setTextureSize(32, 64);
        Booster1SideBR.mirror = true;
        setRotation(Booster1SideBR, 0F, -0.7853982F, 0F);
        Booster1SideRF = new ModelRenderer(this, 0, 9);
        Booster1SideRF.addBox(-1.5F, 0F, 2.6F, 3, 48, 1);
        Booster1SideRF.setRotationPoint(0F, 0F, 0F);
        Booster1SideRF.setTextureSize(32, 64);
        Booster1SideRF.mirror = true;
        setRotation(Booster1SideRF, 0F, -2.356194F, 0F);
        Booster1SideFL = new ModelRenderer(this, 0, 9);
        Booster1SideFL.addBox(-1.5F, 0F, 2.6F, 3, 48, 1);
        Booster1SideFL.setRotationPoint(0F, 0F, 0F);
        Booster1SideFL.setTextureSize(32, 64);
        Booster1SideFL.mirror = true;
        setRotation(Booster1SideFL, 0F, 2.356194F, 0F);
        Booster1NozzleBack = new ModelRenderer(this, 8, 9);
        Booster1NozzleBack.addBox(-1.5F, 43.5F, 19.8F, 3, 2, 1);
        Booster1NozzleBack.setRotationPoint(0F, 0F, 0F);
        Booster1NozzleBack.setTextureSize(32, 64);
        Booster1NozzleBack.mirror = true;
        setRotation(Booster1NozzleBack, -0.3717551F, 0F, 0F);
        Booster1NozzleLeft = new ModelRenderer(this, 8, 9);
        Booster1NozzleLeft.addBox(-1.5F, 43.5F, 19.8F, 3, 2, 1);
        Booster1NozzleLeft.setRotationPoint(0F, 0F, 0F);
        Booster1NozzleLeft.setTextureSize(32, 64);
        Booster1NozzleLeft.mirror = true;
        setRotation(Booster1NozzleLeft, -0.3717551F, 1.570796F, 0F);
        Booster1NozzleFront = new ModelRenderer(this, 8, 9);
        Booster1NozzleFront.addBox(-1.5F, 43.5F, 19.8F, 3, 2, 1);
        Booster1NozzleFront.setRotationPoint(0F, 0F, 0F);
        Booster1NozzleFront.setTextureSize(32, 64);
        Booster1NozzleFront.mirror = true;
        setRotation(Booster1NozzleFront, -0.3717551F, 3.141593F, 0F);
        Booster1NozzleRight = new ModelRenderer(this, 8, 9);
        Booster1NozzleRight.addBox(-1.5F, 43.5F, 19.8F, 3, 2, 1);
        Booster1NozzleRight.setRotationPoint(0F, 0F, 0F);
        Booster1NozzleRight.setTextureSize(32, 64);
        Booster1NozzleRight.mirror = true;
        setRotation(Booster1NozzleRight, -0.3717551F, -1.570796F, 0F);
        Booster1NozzleLB = new ModelRenderer(this, 8, 12);
        Booster1NozzleLB.addBox(-1F, 43.5F, 19.8F, 2, 2, 1);
        Booster1NozzleLB.setRotationPoint(0F, 0F, 0F);
        Booster1NozzleLB.setTextureSize(32, 64);
        Booster1NozzleLB.mirror = true;
        setRotation(Booster1NozzleLB, -0.3717551F, 0.7853982F, 0F);
        Booster1NozzleBR = new ModelRenderer(this, 8, 12);
        Booster1NozzleBR.addBox(-1F, 43.5F, 19.8F, 2, 2, 1);
        Booster1NozzleBR.setRotationPoint(0F, 0F, 0F);
        Booster1NozzleBR.setTextureSize(32, 64);
        Booster1NozzleBR.mirror = true;
        setRotation(Booster1NozzleBR, -0.3717551F, -0.7853982F, 0F);
        Booster1NozzleFL = new ModelRenderer(this, 8, 12);
        Booster1NozzleFL.addBox(-1F, 43.5F, 19.8F, 2, 2, 1);
        Booster1NozzleFL.setRotationPoint(0F, 0F, 0F);
        Booster1NozzleFL.setTextureSize(32, 64);
        Booster1NozzleFL.mirror = true;
        setRotation(Booster1NozzleFL, -0.3717551F, 2.356194F, 0F);
        Booster1NozzleRF = new ModelRenderer(this, 8, 12);
        Booster1NozzleRF.addBox(-1F, 43.5F, 19.8F, 2, 2, 1);
        Booster1NozzleRF.setRotationPoint(0F, 0F, 0F);
        Booster1NozzleRF.setTextureSize(32, 64);
        Booster1NozzleRF.mirror = true;
        setRotation(Booster1NozzleRF, -0.3717551F, -2.356194F, 0F);
        Booster1ConeBack = new ModelRenderer(this, 0, 6);
        Booster1ConeBack.addBox(-1.5F, 0.7F, 1.3F, 3, 2, 1);
        Booster1ConeBack.setRotationPoint(0F, 0F, 0F);
        Booster1ConeBack.setTextureSize(32, 64);
        Booster1ConeBack.mirror = true;
        setRotation(Booster1ConeBack, 0.8726646F, 0F, 0F);
        Booster1ConeLB = new ModelRenderer(this, 8, 6);
        Booster1ConeLB.addBox(-1F, 0.7F, 1.3F, 2, 2, 1);
        Booster1ConeLB.setRotationPoint(0F, 0F, 0F);
        Booster1ConeLB.setTextureSize(32, 64);
        Booster1ConeLB.mirror = true;
        setRotation(Booster1ConeLB, 0.8726646F, 0.7853982F, 0F);
        Booster1ConeLeft = new ModelRenderer(this, 0, 6);
        Booster1ConeLeft.addBox(-1.5F, 0.7F, 1.3F, 3, 2, 1);
        Booster1ConeLeft.setRotationPoint(0F, 0F, 0F);
        Booster1ConeLeft.setTextureSize(32, 64);
        Booster1ConeLeft.mirror = true;
        setRotation(Booster1ConeLeft, 0.8726646F, 1.570796F, 0F);
        Booster1ConeFL = new ModelRenderer(this, 8, 6);
        Booster1ConeFL.addBox(-1F, 0.7F, 1.3F, 2, 2, 1);
        Booster1ConeFL.setRotationPoint(0F, 0F, 0F);
        Booster1ConeFL.setTextureSize(32, 64);
        Booster1ConeFL.mirror = true;
        setRotation(Booster1ConeFL, 0.8726646F, 2.356194F, 0F);
        Booster1ConeFront = new ModelRenderer(this, 0, 6);
        Booster1ConeFront.addBox(-1.5F, 0.7F, 1.3F, 3, 2, 1);
        Booster1ConeFront.setRotationPoint(0F, 0F, 0F);
        Booster1ConeFront.setTextureSize(32, 64);
        Booster1ConeFront.mirror = true;
        setRotation(Booster1ConeFront, 0.8726646F, 3.141593F, 0F);
        Booster1ConeRF = new ModelRenderer(this, 8, 6);
        Booster1ConeRF.addBox(-1F, 0.7F, 1.3F, 2, 2, 1);
        Booster1ConeRF.setRotationPoint(0F, 0F, 0F);
        Booster1ConeRF.setTextureSize(32, 64);
        Booster1ConeRF.mirror = true;
        setRotation(Booster1ConeRF, 0.8726646F, -2.356194F, 0F);
        Booster1ConeRight = new ModelRenderer(this, 0, 6);
        Booster1ConeRight.addBox(-1.5F, 0.7F, 1.3F, 3, 2, 1);
        Booster1ConeRight.setRotationPoint(0F, 0F, 0F);
        Booster1ConeRight.setTextureSize(32, 64);
        Booster1ConeRight.mirror = true;
        setRotation(Booster1ConeRight, 0.8726646F, -1.570796F, 0F);
        Booster1ConeBR = new ModelRenderer(this, 8, 6);
        Booster1ConeBR.addBox(-1F, 0.7F, 1.3F, 2, 2, 1);
        Booster1ConeBR.setRotationPoint(0F, 0F, 0F);
        Booster1ConeBR.setTextureSize(32, 64);
        Booster1ConeBR.mirror = true;
        setRotation(Booster1ConeBR, 0.8726646F, -0.7853982F, 0F);
        Booster1ConeTop = new ModelRenderer(this, 0, 0);
        Booster1ConeTop.addBox(-2F, -1.3F, -2F, 4, 2, 4);
        Booster1ConeTop.setRotationPoint(0F, 0F, 0F);
        Booster1ConeTop.setTextureSize(32, 64);
        Booster1ConeTop.mirror = true;
        setRotation(Booster1ConeTop, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Booster1SideBack.render(f5);
        Booster1SideLeft.render(f5);
        Booster1SideFront.render(f5);
        Booster1SideRight.render(f5);
        Booster1SideLB.render(f5);
        Booster1SideBR.render(f5);
        Booster1SideRF.render(f5);
        Booster1SideFL.render(f5);
        Booster1NozzleBack.render(f5);
        Booster1NozzleLeft.render(f5);
        Booster1NozzleFront.render(f5);
        Booster1NozzleRight.render(f5);
        Booster1NozzleLB.render(f5);
        Booster1NozzleBR.render(f5);
        Booster1NozzleFL.render(f5);
        Booster1NozzleRF.render(f5);
        Booster1ConeBack.render(f5);
        Booster1ConeLB.render(f5);
        Booster1ConeLeft.render(f5);
        Booster1ConeFL.render(f5);
        Booster1ConeFront.render(f5);
        Booster1ConeRF.render(f5);
        Booster1ConeRight.render(f5);
        Booster1ConeBR.render(f5);
        Booster1ConeTop.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }
}
