// Date: 2016-06-27 16:19:13
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.fogo01.scicraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelFlag extends ModelBase {
    //fields
    ModelRenderer Pole;
    ModelRenderer Knob;
    ModelRenderer KnobTop;
    ModelRenderer Flag;

    public ModelFlag() {
        textureWidth = 64;
        textureHeight = 64;
    
        Pole = new ModelRenderer(this, 0, 0);
        Pole.addBox(-0.5F, -60F, 0F, 1, 60, 1);
        Pole.setRotationPoint(0F, 0F, 0F);
        Pole.setTextureSize(64, 64);
        Pole.mirror = true;
        setRotation(Pole, -0.1745329F, 0F, 0F);
        Knob = new ModelRenderer(this, 4, 2);
        Knob.addBox(-1F, -61F, -0.5F, 2, 1, 2);
        Knob.setRotationPoint(0F, 0F, 0F);
        Knob.setTextureSize(64, 64);
        Knob.mirror = true;
        setRotation(Knob, -0.1745329F, 0F, 0F);
        KnobTop = new ModelRenderer(this, 4, 0);
        KnobTop.addBox(-0.5F, -62F, 0F, 1, 1, 1);
        KnobTop.setRotationPoint(0F, 0F, 0F);
        KnobTop.setTextureSize(64, 64);
        KnobTop.mirror = true;
        setRotation(KnobTop, -0.1745329F, 0F, 0F);
        Flag = new ModelRenderer(this, 4, 0);
        Flag.addBox(-0.5F, -60F, 1F, 1, 12, 16);
        Flag.setRotationPoint(0F, 0F, 0F);
        Flag.setTextureSize(64, 64);
        Flag.mirror = true;
        setRotation(Flag, -0.1745329F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Pole.render(f5);
        Knob.render(f5);
        KnobTop.render(f5);
        Flag.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
  
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
