// Date: 2016-06-23 14:04:30
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.fogo01.scicraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelFlag extends ModelBase {
    //fields
    ModelRenderer Shaft;
    ModelRenderer Flag;

    public ModelFlag() {
        textureWidth = 32;
        textureHeight = 32;

        Shaft = new ModelRenderer(this, 0, 0);
        Shaft.addBox(-6F, -16F, 0F, 1, 16, 1);
        Shaft.setRotationPoint(0F, 0F, 0F);
        Shaft.setTextureSize(32, 32);
        Shaft.mirror = true;
        setRotation(Shaft, -0.2617994F, 0F, 0F);
        Flag = new ModelRenderer(this, 4, 0);
        Flag.addBox(-6F, -16F, 1F, 1, 6, 8);
        Flag.setRotationPoint(0F, 0F, 0F);
        Flag.setTextureSize(32, 32);
        Flag.mirror = true;
        setRotation(Flag, -0.2617994F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Shaft.render(f5);
        Flag.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }
}
