// Date: 2016-06-11 12:15:03
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.fogo01.scicraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPlasmaLauncher extends ModelBase {
    //fields
    ModelRenderer Handle;
    ModelRenderer BarrelBottom;
    ModelRenderer BarrelRight;
    ModelRenderer BarrelTop;
    ModelRenderer BarrelLeft;
    ModelRenderer BarrelBack;
    ModelRenderer Scope;
  
    public ModelPlasmaLauncher() {
        textureWidth = 64;
        textureHeight = 32;

        Handle = new ModelRenderer(this, 0, 0);
        Handle.addBox(-1F, -2F, -2F, 2, 3, 2);
        Handle.setRotationPoint(0F, 0F, 0F);
        Handle.setTextureSize(64, 32);
        Handle.mirror = true;
        setRotation(Handle, 0F, 0F, 0F);
        BarrelBottom = new ModelRenderer(this, 8, 0);
        BarrelBottom.addBox(-7F, -3F, -1F, 12, 1, 2);
        BarrelBottom.setRotationPoint(0F, 0F, 0F);
        BarrelBottom.setTextureSize(64, 32);
        BarrelBottom.mirror = true;
        setRotation(BarrelBottom, 0F, 1.570796F, 0F);
        BarrelRight = new ModelRenderer(this, 8, 0);
        BarrelRight.addBox(-7F, 1F, -5F, 12, 1, 2);
        BarrelRight.setRotationPoint(0F, 0F, 0F);
        BarrelRight.setTextureSize(64, 32);
        BarrelRight.mirror = true;
        setRotation(BarrelRight, -1.570796F, 1.570796F, 0F);
        BarrelTop = new ModelRenderer(this, 8, 0);
        BarrelTop.addBox(-7F, 5F, -1F, 12, 1, 2);
        BarrelTop.setRotationPoint(0F, 0F, 0F);
        BarrelTop.setTextureSize(64, 32);
        BarrelTop.mirror = true;
        setRotation(BarrelTop, 3.141593F, 1.570796F, 0F);
        BarrelLeft = new ModelRenderer(this, 8, 0);
        BarrelLeft.addBox(-7F, 1F, 3F, 12, 1, 2);
        BarrelLeft.setRotationPoint(0F, 0F, 0F);
        BarrelLeft.setTextureSize(64, 32);
        BarrelLeft.mirror = true;
        setRotation(BarrelLeft, 1.570796F, 1.570796F, 0F);
        BarrelBack = new ModelRenderer(this, 8, 3);
        BarrelBack.addBox(-1F, -5F, 6F, 2, 2, 1);
        BarrelBack.setRotationPoint(0F, 0F, 0F);
        BarrelBack.setTextureSize(64, 32);
        BarrelBack.mirror = true;
        setRotation(BarrelBack, 0F, 0F, 0F);
        Scope = new ModelRenderer(this, 14, 3);
        Scope.addBox(-3F, -7F, -0.5F, 8, 1, 1);
        Scope.setRotationPoint(0F, 0F, 0F);
        Scope.setTextureSize(64, 32);
        Scope.mirror = true;
        setRotation(Scope, 0F, 1.570796F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Handle.render(f5);
        BarrelBottom.render(f5);
        BarrelRight.render(f5);
        BarrelTop.render(f5);
        BarrelLeft.render(f5);
        BarrelBack.render(f5);
        Scope.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
