// Date: 2017-01-25 20:12:25
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.fogo01.scicraft.models;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelJetpack extends ModelBiped {
    //fields
    ModelRenderer LeftLeftPart;
    ModelRenderer LeftFrontPart;
    ModelRenderer LeftBackPart;
    ModelRenderer LeftRightPart;
    ModelRenderer LeftTopPart;
    ModelRenderer LeftTopTopPart;
    ModelRenderer LeftBottomLeftPart;
    ModelRenderer LeftBottomFrontPart;
    ModelRenderer LeftBottomRightPart;
    ModelRenderer LeftBottomBackPart;
    ModelRenderer RightLeftPart;
    ModelRenderer RightFrontPart;
    ModelRenderer RightBackPart;
    ModelRenderer RightRightPart;
    ModelRenderer RightTopPart;
    ModelRenderer RightTopTopPart;
    ModelRenderer RightBottomLeftPart;
    ModelRenderer RightBottomFrontPart;
    ModelRenderer RightBottomRightPart;
    ModelRenderer RightBottomBackPart;
    ModelRenderer Middle;
    ModelRenderer Belt;
    ModelRenderer LeftStrap;
    ModelRenderer RightStrap;
  
    public ModelJetpack() {
        textureWidth = 64;
        textureHeight = 32;

        LeftLeftPart = new ModelRenderer(this, 0, 10);
        LeftLeftPart.addBox(3F, 2F, -5F, 2, 8, 1);
        LeftLeftPart.setRotationPoint(0F, 0F, 0F);
        LeftLeftPart.setTextureSize(64, 32);
        LeftLeftPart.mirror = true;
        setRotation(LeftLeftPart, 0F, -1.570796F, 0F);
        LeftFrontPart = new ModelRenderer(this, 6, 10);
        LeftFrontPart.addBox(2F, 2F, 2F, 2, 8, 1);
        LeftFrontPart.setRotationPoint(0F, 0F, 0F);
        LeftFrontPart.setTextureSize(64, 32);
        LeftFrontPart.mirror = true;
        setRotation(LeftFrontPart, 0F, 0F, 0F);
        LeftBackPart = new ModelRenderer(this, 12, 10);
        LeftBackPart.addBox(-4F, 2F, -6F, 2, 8, 1);
        LeftBackPart.setRotationPoint(0F, 0F, 0F);
        LeftBackPart.setTextureSize(64, 32);
        LeftBackPart.mirror = true;
        setRotation(LeftBackPart, 0F, 3.141593F, 0F);
        LeftRightPart = new ModelRenderer(this, 18, 10);
        LeftRightPart.addBox(-5F, 2F, 1F, 2, 8, 1);
        LeftRightPart.setRotationPoint(0F, 0F, 0F);
        LeftRightPart.setTextureSize(64, 32);
        LeftRightPart.mirror = true;
        setRotation(LeftRightPart, 0F, 1.570796F, 0F);
        LeftTopPart = new ModelRenderer(this, 24, 10);
        LeftTopPart.addBox(2F, 0.5F, 3F, 2, 9, 2);
        LeftTopPart.setRotationPoint(0F, 0F, 0F);
        LeftTopPart.setTextureSize(64, 32);
        LeftTopPart.mirror = true;
        setRotation(LeftTopPart, 0F, 0F, 0F);
        LeftTopTopPart = new ModelRenderer(this, 24, 8);
        LeftTopTopPart.addBox(2.5F, 0F, 3.5F, 1, 1, 1);
        LeftTopTopPart.setRotationPoint(0F, 0F, 0F);
        LeftTopTopPart.setTextureSize(64, 32);
        LeftTopTopPart.mirror = true;
        setRotation(LeftTopTopPart, 0F, 0F, 0F);
        LeftBottomLeftPart = new ModelRenderer(this, 0, 19);
        LeftBottomLeftPart.addBox(3F, 10.5F, -1.3F, 2, 2, 1);
        LeftBottomLeftPart.setRotationPoint(0F, 0F, 0F);
        LeftBottomLeftPart.setTextureSize(64, 32);
        LeftBottomLeftPart.mirror = true;
        setRotation(LeftBottomLeftPart, -0.3490659F, -1.570796F, 0F);
        LeftBottomFrontPart = new ModelRenderer(this, 6, 19);
        LeftBottomFrontPart.addBox(2F, 10F, 2F, 2, 2, 1);
        LeftBottomFrontPart.setRotationPoint(0F, 0F, 0F);
        LeftBottomFrontPart.setTextureSize(64, 32);
        LeftBottomFrontPart.mirror = true;
        setRotation(LeftBottomFrontPart, 0F, 0F, 0F);
        LeftBottomRightPart = new ModelRenderer(this, 12, 19);
        LeftBottomRightPart.addBox(-5F, 8.5F, 4.3F, 2, 2, 1);
        LeftBottomRightPart.setRotationPoint(0F, 0F, 0F);
        LeftBottomRightPart.setTextureSize(64, 32);
        LeftBottomRightPart.mirror = true;
        setRotation(LeftBottomRightPart, -0.3490659F, 1.570796F, 0F);
        LeftBottomBackPart = new ModelRenderer(this, 18, 19);
        LeftBottomBackPart.addBox(-4F, 10.8F, -2.25F, 2, 2, 1);
        LeftBottomBackPart.setRotationPoint(0F, 0F, 0F);
        LeftBottomBackPart.setTextureSize(64, 32);
        LeftBottomBackPart.mirror = true;
        setRotation(LeftBottomBackPart, -0.3490659F, 3.141593F, 0F);
        RightLeftPart = new ModelRenderer(this, 0, 10);
        RightLeftPart.addBox(3F, 2F, 1F, 2, 8, 1);
        RightLeftPart.setRotationPoint(0F, 0F, 0F);
        RightLeftPart.setTextureSize(64, 32);
        RightLeftPart.mirror = true;
        setRotation(RightLeftPart, 0F, -1.570796F, 0F);
        RightFrontPart = new ModelRenderer(this, 6, 10);
        RightFrontPart.addBox(-4F, 2F, 2F, 2, 8, 1);
        RightFrontPart.setRotationPoint(0F, 0F, 0F);
        RightFrontPart.setTextureSize(64, 32);
        RightFrontPart.mirror = true;
        setRotation(RightFrontPart, 0F, 0F, 0F);
        RightBackPart = new ModelRenderer(this, 12, 10);
        RightBackPart.addBox(2F, 2F, -6F, 2, 8, 1);
        RightBackPart.setRotationPoint(0F, 0F, 0F);
        RightBackPart.setTextureSize(64, 32);
        RightBackPart.mirror = true;
        setRotation(RightBackPart, 0F, 3.141593F, 0F);
        RightRightPart = new ModelRenderer(this, 18, 10);
        RightRightPart.addBox(-5F, 2F, -5F, 2, 8, 1);
        RightRightPart.setRotationPoint(0F, 0F, 0F);
        RightRightPart.setTextureSize(64, 32);
        RightRightPart.mirror = true;
        setRotation(RightRightPart, 0F, 1.570796F, 0F);
        RightTopPart = new ModelRenderer(this, 24, 10);
        RightTopPart.addBox(-4F, 0.5F, 3F, 2, 9, 2);
        RightTopPart.setRotationPoint(0F, 0F, 0F);
        RightTopPart.setTextureSize(64, 32);
        RightTopPart.mirror = true;
        setRotation(RightTopPart, 0F, 0F, 0F);
        RightTopTopPart = new ModelRenderer(this, 24, 8);
        RightTopTopPart.addBox(-3.5F, 0F, 3.5F, 1, 1, 1);
        RightTopTopPart.setRotationPoint(0F, 0F, 0F);
        RightTopTopPart.setTextureSize(64, 32);
        RightTopTopPart.mirror = true;
        setRotation(RightTopTopPart, 0F, 0F, 0F);
        RightBottomLeftPart = new ModelRenderer(this, 0, 19);
        RightBottomLeftPart.addBox(3F, 8.6F, 4.3F, 2, 2, 1);
        RightBottomLeftPart.setRotationPoint(0F, 0F, 0F);
        RightBottomLeftPart.setTextureSize(64, 32);
        RightBottomLeftPart.mirror = true;
        setRotation(RightBottomLeftPart, -0.3490659F, -1.570796F, 0F);
        RightBottomFrontPart = new ModelRenderer(this, 6, 19);
        RightBottomFrontPart.addBox(-4F, 10F, 2F, 2, 2, 1);
        RightBottomFrontPart.setRotationPoint(0F, 0F, 0F);
        RightBottomFrontPart.setTextureSize(64, 32);
        RightBottomFrontPart.mirror = true;
        setRotation(RightBottomFrontPart, 0F, 0F, 0F);
        RightBottomRightPart = new ModelRenderer(this, 12, 19);
        RightBottomRightPart.addBox(-5F, 10.6F, -1.3F, 2, 2, 1);
        RightBottomRightPart.setRotationPoint(0F, 0F, 0F);
        RightBottomRightPart.setTextureSize(64, 32);
        RightBottomRightPart.mirror = true;
        setRotation(RightBottomRightPart, -0.3490659F, 1.570796F, 0F);
        RightBottomBackPart = new ModelRenderer(this, 18, 19);
        RightBottomBackPart.addBox(2F, 10.8F, -2.25F, 2, 2, 1);
        RightBottomBackPart.setRotationPoint(0F, 0F, 0F);
        RightBottomBackPart.setTextureSize(64, 32);
        RightBottomBackPart.mirror = true;
        setRotation(RightBottomBackPart, -0.3490659F, 3.141593F, 0F);
        Middle = new ModelRenderer(this, 32, 10);
        Middle.addBox(-1F, 3F, -4.5F, 2, 4, 1);
        Middle.setRotationPoint(0F, 0F, 0F);
        Middle.setTextureSize(64, 32);
        Middle.mirror = true;
        setRotation(Middle, 0F, 3.141593F, 0F);
        Belt = new ModelRenderer(this, 0, 0);
        Belt.addBox(-4.5F, 4.5F, -2.5F, 9, 2, 5);
        Belt.setRotationPoint(0F, 0F, 0F);
        Belt.setTextureSize(64, 32);
        Belt.mirror = true;
        setRotation(Belt, 0F, 0F, 0F);
        LeftStrap = new ModelRenderer(this, 28, 0);
        LeftStrap.addBox(2.5F, -0.5F, 0F, 1, 5, 5);
        LeftStrap.setRotationPoint(0F, 0F, -2.5F);
        LeftStrap.setTextureSize(64, 32);
        LeftStrap.mirror = true;
        setRotation(LeftStrap, 0F, 0F, 0F);
        RightStrap = new ModelRenderer(this, 28, 0);
        RightStrap.addBox(-3.5F, -0.5F, 0F, 1, 5, 5);
        RightStrap.setRotationPoint(0F, 0F, -2.5F);
        RightStrap.setTextureSize(64, 32);
        RightStrap.mirror = true;
        setRotation(RightStrap, 0F, 0F, 0F);

        this.bipedBody.addChild(LeftLeftPart);
        this.bipedBody.addChild(LeftFrontPart);
        this.bipedBody.addChild(LeftBackPart);
        this.bipedBody.addChild(LeftRightPart);
        this.bipedBody.addChild(LeftTopPart);
        this.bipedBody.addChild(LeftTopTopPart);
        this.bipedBody.addChild(LeftBottomLeftPart);
        this.bipedBody.addChild(LeftBottomFrontPart);
        this.bipedBody.addChild(LeftBottomRightPart);
        this.bipedBody.addChild(LeftBottomBackPart);
        this.bipedBody.addChild(RightLeftPart);
        this.bipedBody.addChild(RightFrontPart);
        this.bipedBody.addChild(RightBackPart);
        this.bipedBody.addChild(RightRightPart);
        this.bipedBody.addChild(RightTopPart);
        this.bipedBody.addChild(RightTopTopPart);
        this.bipedBody.addChild(RightBottomLeftPart);
        this.bipedBody.addChild(RightBottomFrontPart);
        this.bipedBody.addChild(RightBottomRightPart);
        this.bipedBody.addChild(RightBottomBackPart);
        this.bipedBody.addChild(Middle);
        this.bipedBody.addChild(Belt);
        this.bipedBody.addChild(LeftStrap);
        this.bipedBody.addChild(RightStrap);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        LeftLeftPart.render(f5);
        LeftFrontPart.render(f5);
        LeftBackPart.render(f5);
        LeftRightPart.render(f5);
        LeftTopPart.render(f5);
        LeftTopTopPart.render(f5);
        LeftBottomLeftPart.render(f5);
        LeftBottomFrontPart.render(f5);
        LeftBottomRightPart.render(f5);
        LeftBottomBackPart.render(f5);
        RightLeftPart.render(f5);
        RightFrontPart.render(f5);
        RightBackPart.render(f5);
        RightRightPart.render(f5);
        RightTopPart.render(f5);
        RightTopTopPart.render(f5);
        RightBottomLeftPart.render(f5);
        RightBottomFrontPart.render(f5);
        RightBottomRightPart.render(f5);
        RightBottomBackPart.render(f5);
        Middle.render(f5);
        Belt.render(f5);
        LeftStrap.render(f5);
        RightStrap.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
  
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }
}
